"""Contains all configs"""

DATA_FILE = "./urdu_sentences.pkl"
SENTENCE_MAX_LENGTH = 150
SENTENCE_MIN_LENGTH = 10

HIDDEN_UNITS = 256
NUM_BLOCKS = 6
NUM_HEADS = 8
DROPOUT_RATE = 0.2
ENCODER_NUM_BANKS = 16
NUM_HIGHWAYNET_BLOCKS = 4

NUM_EPOCHS = 20
BATCH_SIZE = 128
LEARNING_RATE = 0.0001
LOG_DIR = 'LOG_DIR'
SAVE_DIR = "RESULTS"
